modLoader="javafml"
loaderVersion="[37,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="torment"
version="${file.jarVersion}"
displayName="Torment"
displayURL="https://www.curseforge.com/minecraft/mc-mods/torment"
updateJSONURL="https://assets.melanx.de/updates/torment.json"
authors="noeppi_noeppi"
description="""
"""

[[dependencies.torment]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.74,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.torment]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.torment]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1-2.1.2,)"
    ordering="NONE"
    side="BOTH"